## Understanding Tensors:
 * What are tensors?
 * Creating tensors in PyTorch
 * Tensor operations and manipulations

In [ ]:
from IPython.display import Image as IPythonImage
%matplotlib inline


In [ ]:
import torch
import numpy as np

print('PyTorch version:', torch.__version__)

print('Is GPU available:', torch.cuda.is_available())

np.set_printoptions(precision=3)

PyTorch version: 2.1.0+cu121
Is GPU available: False


## Creating tensors

In [ ]:
# creating tensor from a list

mylist = [1, 2, 3, 4]
mytensor = torch.tensor(mylist)

print('mytensor:', mytensor)
print('mytensor shape:', mytensor.shape)
print('mytensor dtype:', mytensor.dtype)

print('mytensor size:', mytensor.size())
print('mytensor dims:', mytensor.dim())
print('mytensor number of elementes:', mytensor.numel())

mytensor: tensor([1, 2, 3, 4])
mytensor shape: torch.Size([4])
mytensor dtype: torch.int64
mytensor size: torch.Size([4])
mytensor dims: 1
mytensor number of elementes: 4


In [ ]:
# creating tensor from a list

mylist = [[1, 2], [3, 4], [5, 6]]
mytensor = torch.tensor(mylist)

print('mytensor:', mytensor)
print('mytensor shape:', mytensor.shape)
print('mytensor dtype:', mytensor.dtype)

print('mytensor size:', mytensor.size())
print('mytensor dims:', mytensor.dim())
print('mytensor number of elementes:', mytensor.numel())

mytensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])
mytensor shape: torch.Size([3, 2])
mytensor dtype: torch.int64
mytensor size: torch.Size([3, 2])
mytensor dims: 2
mytensor number of elementes: 6


### Initializing a tensor of 1s and 0s

In [ ]:
a = torch.ones((2, 5))
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
b = torch.zeros(4, 3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Initializing a tensor of random

In [ ]:
c = torch.rand(3, 2)
c

tensor([[0.9242, 0.2289],
        [0.6437, 0.3083],
        [0.3924, 0.5414]])

### Type conversion (casting)

In [ ]:
c1 = torch.rand(3, 2)
print('dtype of tensor c1:', c1.dtype)

c2 = c1.to(torch.float64)
print('dtype of tensor c2:', c2.dtype)

dtype of tensor c1: torch.float32
dtype of tensor c2: torch.float64


### Manipulating tensors via shaping operations

In [ ]:
a1 = torch.arange(24)
a1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [ ]:
# reshape to a 2D tensor
a2 = a1.reshape(3, 8)

In [ ]:
# transpose a tensor:
a2_t = a2.T   # or using a2.transpose(1, 0)
print('a2 shaoe is:', a2.shape)
print('a2_t shape is:', a2_t.shape)
a2_t

a2 shaoe is: torch.Size([3, 8])
a2_t shape is: torch.Size([8, 3])


tensor([[ 0,  8, 16],
        [ 1,  9, 17],
        [ 2, 10, 18],
        [ 3, 11, 19],
        [ 4, 12, 20],
        [ 5, 13, 21],
        [ 6, 14, 22],
        [ 7, 15, 23]])

In [ ]:
# add a dimension of size 1 at the beginning
a3 = a2.unsqueeze(0)
print('a3 shape:', a3.shape)

# add a dimension of size 1 at the end
a4 = a2.unsqueeze(-1)
print('a4 shape:', a4.shape)

a3 shape: torch.Size([1, 3, 8])
a4 shape: torch.Size([3, 8, 1])


In [ ]:
# remove the dimension of size 1:
a5 = a4.squeeze()
print('a5 shape:', a5.shape)

a5 shape: torch.Size([3, 8])


## Mathematical operations

In [ ]:
torch.manual_seed(1)

x = torch.rand(4, 8)
print('x:', x.shape)

# mean of all
mean_x = torch.mean(x)  # or using x.mean()
print('mean_x:', mean_x)

# sum of all
sum_x = torch.sum(x)  # or using x.sum()
print('sum_x:', sum_x)

# mean of rows
mean_x_rows = torch.mean(x, dim=1)
print('mean_of_rows:', mean_x_rows)

# sum of columns
sum_x_columns = torch.sum(x, dim=0)
print('sum_x_columns:', sum_x_columns)

x: torch.Size([4, 8])
mean_x: tensor(0.5305)
sum_x: tensor(16.9775)
mean_of_rows: tensor([0.5194, 0.5097, 0.4844, 0.6086])
sum_x_columns: tensor([2.2394, 1.7400, 2.7769, 2.6867, 1.0369, 2.1130, 1.9166, 2.4680])


In [ ]:
# L1 norm:
norml1_x = torch.linalg.norm(x, ord=1, dim=-1)
print('norml1_x:', norml1_x)

# L2 norm:
norml1_x = torch.linalg.norm(x, ord=2, dim=-1)
print('norml1_x:', norml1_x)

norml1_x: tensor([4.1553, 4.0779, 3.8755, 4.8687])
norml1_x: tensor([1.6497, 1.4768, 1.5084, 1.9071])


In [ ]:
# matrix multiplication
x_squared = torch.matmul(x.T, x)
print('x_squared shape is:', x_squared.shape)

# w^T x
w = torch.normal(mean=0, std=1, size=(4, 5))
wx = torch.matmul(w.T, x)
print('w^Tx shape is:', wx.shape)

x_squared shape is: torch.Size([8, 8])
w^Tx shape is: torch.Size([5, 8])


## Splitting and concatenating tensors

In [ ]:
x = torch.rand(6)
print('x:', x.shape)

#  splitting tensors into equally sized chunks
x_splits = torch.chunk(x, 3)
print('splitted tensors:', x_splits)

# splitting tensors into chunks with arbitrary sizes
t_splits = torch.split(x, split_size_or_sections=[2, 4])
print('splitted tensors:', t_splits)


x: torch.Size([6])
splitted tensors: (tensor([0.7576, 0.2793]), tensor([0.4031, 0.7347]), tensor([0.0293, 0.7999]))
splitted tensors: (tensor([0.7576, 0.2793]), tensor([0.4031, 0.7347, 0.0293, 0.7999]))


In [ ]:
#  Concatenating two tensors

a = torch.zeros((1, 3))

#  Concatenating tensors across rows (vertically)
b1 = torch.cat((a, a+1, a+2), axis=0)
b2 = torch.vstack((a, a+1, a+2))
print('b1:', b1)
print('b2:', b2)

#  Concatenating tensors across columns (horizontally)
c1 = torch.cat((a, a+1, a+2), axis=1)
c2 = torch.cat((a, a+1, a+2), axis=1)
print('c1:', c1)
print('c2:', c2)

b1: tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.]])
b2: tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.]])
c1: tensor([[0., 0., 0., 1., 1., 1., 2., 2., 2.]])
c2: tensor([[0., 0., 0., 1., 1., 1., 2., 2., 2.]])


## Input pipeline in PyTorch

### Creating PyTorch Datasets and DataLoaders from tensors

In [ ]:
# pytorch DataLoader

from torch.utils.data import DataLoader

t = torch.tensor([1, 2, 3, 4, 5])
data_loader = DataLoader(t, batch_size=2, drop_last=False)

for i, batch in enumerate(data_loader, 1):
    print(f'batch {i}:', batch)

batch 1: tensor([1, 2])
batch 2: tensor([3, 4])
batch 3: tensor([5])


###  Building a custom dataset

In [ ]:
from torch.utils.data import Dataset

#  Pytorch Dataset
class CustomDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]


In [ ]:
t_x = torch.rand([10, 3], dtype=torch.float32)
t_y = torch.arange(10)
custom_dataset = CustomDataset(t_x, t_y)


data_loader = DataLoader(dataset=custom_dataset, batch_size=2, shuffle=True)

for i, (x, y) in enumerate(data_loader, 1):
    print(f'batch {i}: \n',
          'x:', x, '\n y:', y)

batch 1: 
 x: tensor([[0.9389, 0.1708, 0.2383],
        [0.1645, 0.9633, 0.8274]]) 
 y: tensor([1, 5])
batch 2: 
 x: tensor([[0.0295, 0.8628, 0.5924],
        [0.9290, 0.2720, 0.2493]]) 
 y: tensor([0, 4])
batch 3: 
 x: tensor([[0.2043, 0.4691, 0.6969],
        [0.8180, 0.9919, 0.7719]]) 
 y: tensor([3, 8])
batch 4: 
 x: tensor([[0.1798, 0.6175, 0.9004],
        [0.1615, 0.3406, 0.9637]]) 
 y: tensor([7, 6])
batch 5: 
 x: tensor([[0.8449, 0.5858, 0.5920],
        [0.6884, 0.3508, 0.1992]]) 
 y: tensor([2, 9])
